# Generated by Django 2.1.5 on 2019-02-08 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='card-background')),
                ('idkey', models.CharField(default='', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.URLField(blank=True, max_length=300)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category')),
            ],
            options={
                'verbose_name_plural': 'Component',
            },
        ),
    ]
